#!/usr/bin/env python3
"""
freeze_kernel.py — Compile Python kernel modules into a C source file
that embeds them as frozen modules, linked directly into the kernel ELF.

Usage:
    python3 tools/freeze_kernel.py <src_dir> [<src_dir>...] <output.c>

IMPORTANT: must be run with Python 3.14 (matching the compiled libpython3.14.a).
The frozen bytecode opcode numbering must match the cross-compiled CPython 3.14
interpreter. In Python 3.14, RESUME = 128. Using a different Python version
causes the kernel to crash immediately on any Python function entry, since the
interpreter misidentifies the first opcode.

The output is a C file that, when linked into the kernel, merges the frozen
modules from all src_dirs with the existing CPython standard frozen modules
(bootstrap, codecs, io, etc.) from libpython3.14.a. The merge happens at
runtime in install_frozen_kernel(), which must be called BEFORE Py_Initialize().
"""

import marshal
import sys
from pathlib import Path

if sys.version_info[:2] != (3, 14):
    print(f"ERROR: freeze_kernel.py requires Python 3.14, got {sys.version}", file=sys.stderr)
    print("       The frozen bytecode opcode numbering must match the CPython 3.14 interpreter.", file=sys.stderr)
    sys.exit(1)


def freeze_dir(src_dir: Path) -> dict[str, tuple[bytes, bool]]:
    """Walk src_dir, compile every .py to bytecode, return {module_name: (bytecode, is_package)}.

    If src_dir contains an __init__.py it is treated as a package and module
    names are computed relative to src_dir.parent (e.g. kernel/, asyncio/).
    Otherwise it is treated as a lib root and module names are computed
    relative to src_dir itself (e.g. build/stdlib_shim/ which holds enum.py,
    typing.py, collections/, re/, …).
    """
    frozen: dict[str, tuple[bytes, bool]] = {}

    is_lib_root = not (src_dir / "__init__.py").exists()
    root = src_dir if is_lib_root else src_dir.parent

    for py_file in sorted(src_dir.rglob("*.py")):
        rel = py_file.relative_to(root)
        parts = list(rel.with_suffix("").parts)

        if parts[-1] == "__init__":
            module_name = ".".join(parts[:-1])
            is_package = True
        else:
            module_name = ".".join(parts)
            is_package = False

        source = py_file.read_text(encoding="utf-8")
        try:
            code = compile(source, str(py_file), "exec", optimize=0)
        except SyntaxError as e:
            print(f"ERROR: cannot freeze {py_file}: {e}", file=sys.stderr)
            raise SystemExit(1) from e

        bytecode = marshal.dumps(code)
        frozen[module_name] = (bytecode, is_package)

    return frozen


def collect_seed_sources(src_dir: Path) -> dict[str, str]:
    """Collect source files that should be visible in the boot TmpFS."""
    if src_dir.name != "examples":
        return {}

    sources: dict[str, str] = {}
    for source_file in sorted(src_dir.rglob("*")):
        if not source_file.is_file():
            continue
        if source_file.name == "__init__.py":
            continue
        if source_file.suffix not in (".py", ".txt"):
            continue
        rel = source_file.relative_to(src_dir).as_posix()
        sources["/examples/" + rel] = source_file.read_text(encoding="utf-8")
    return sources


def freeze_generated_module(module_name: str, source: str) -> tuple[bytes, bool]:
    code = compile(source, "<generated " + module_name + ">", "exec", optimize=0)
    return (marshal.dumps(code), False)


def emit_c(frozen: dict[str, tuple[bytes, bool]], output: Path) -> None:
    n_modules = len(frozen)

    lines = [
        "/* Auto-generated by tools/freeze_kernel.py — do not edit */",
        '#include "Python.h"',
        "",
    ]

    for name, (bytecode, _) in frozen.items():
        safe = name.replace(".", "_").replace("-", "_")
        array = ", ".join(f"0x{b:02x}" for b in bytecode)
        lines.append(f"static unsigned char _frozen_{safe}[] = {{{array}}};")

    lines += ["", "static const struct _frozen frozen_modules[] = {"]
    for name, (bytecode, is_package) in frozen.items():
        safe = name.replace(".", "_").replace("-", "_")
        size = len(bytecode)
        pkg = 1 if is_package else 0
        lines.append(f'    {{"{name}", _frozen_{safe}, {size}, {pkg}}},')
    lines += ["    {NULL, NULL, 0, 0}", "};", ""]

    # CPython 3.14 checks PyImport_FrozenModules (custom) separately from
    # _PyImport_FrozenStdlib (standard bootstrap/codecs/io/...).  We only
    # need to populate the custom slot with our additions (encodings + kernel).
    # The standard frozen modules remain accessible via _PyImport_FrozenStdlib.
    lines += [
        "void install_frozen_kernel(void) {",
        "    PyImport_FrozenModules = frozen_modules;",
        "}",
        "",
    ]

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {n_modules} frozen modules to {output}")


def main() -> None:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <src_dir> [<src_dir>...] <output.c>", file=sys.stderr)
        sys.exit(1)

    src_dirs = [Path(p).resolve() for p in sys.argv[1:-1]]
    out = Path(sys.argv[-1]).resolve()

    for src_dir in src_dirs:
        if not src_dir.is_dir():
            print(f"Error: {src_dir} is not a directory", file=sys.stderr)
            sys.exit(1)

    frozen: dict[str, tuple[bytes, bool]] = {}
    seed_sources: dict[str, str] = {}
    for src_dir in src_dirs:
        frozen.update(freeze_dir(src_dir))
        seed_sources.update(collect_seed_sources(src_dir))

    if seed_sources:
        source = "SOURCES = " + repr(seed_sources) + "\n"
        frozen["kernel.frozen_sources"] = freeze_generated_module(
            "kernel.frozen_sources",
            source,
        )

    emit_c(frozen, out)


if __name__ == "__main__":
    main()
